// Code generated by running "go generate" in golang.org/x/text. DO NOT EDIT.

package main

import (
	"golang.org/x/text/language"
	"golang.org/x/text/message"
	"golang.org/x/text/message/catalog"
)

type dictionary struct {
	index []uint32
	data  string
}

func (d *dictionary) Lookup(key string) (data string, ok bool) {
	p, ok := messageKeyToIndex[key]
	if !ok {
		return "", false
	}
	start, end := d.index[p], d.index[p+1]
	if start == end {
		return "", false
	}
	return d.data[start:end], true
}

func init() {
	dict := map[string]catalog.Dictionary{
		"en_US": &dictionary{index: en_USIndex, data: en_USData},
	}
	fallback := language.MustParse("en-US")
	cat, err := catalog.NewFromMap(dict, catalog.Fallback(fallback))
	if err != nil {
		panic(err)
	}
	message.DefaultCatalog = cat
}

var messageKeyToIndex = map[string]int{
	"%v\n\nTry running '%s -config' to generate a default config file.": 63,
	"Add":                              112,
	"Add Contact":                      94,
	"Address":                          95,
	"Are you sure you want to quit?":   108,
	"Away":                             102,
	"Busy":                             103,
	"Cancel":                           3,
	"Channels":                         97,
	"Commands":                         113,
	"Complete":                         2,
	"Conversation":                     98,
	"Conversations":                    99,
	"DEBUG":                            55,
	"Error closing roster stream: %q":  92,
	"Error closing the connection: %q": 84,
	"Error encoding default config as TOML: %v": 62,
	"Error going offline: %q":                   83,
	"Error while handling XMPP streams: %q":     82,
	"Exec":                                      115,
	"Join":                                      110,
	"Join Channel":                              111,
	"Loading commands…":                         114,
	"Logs":                                      104,
	"Name":                                      96,
	"Next":                                      1,
	"Offline":                                   100,
	"Online":                                    101,
	"Prev":                                      0,
	"Quit":                                      109,
	"RECV":                                      56,
	"Remove":                                    105,
	"Remove this channel?":                      107,
	"Remove this contact from your roster?":     106,
	"SENT":                                      57,
	"To fix this, contact your server administrator and ask them to enable %q": 89,
	"Usage of communiqué:\n\n": 54,
	"Your server does not support bookmark unification, an important feature that stops newer clients from seeing a different list of chat rooms than older clients that do not yet support the latest features.": 90,
	"account %q not found in config file":                                         66,
	"caps cache hit for %s: %s:%s":                                                48,
	"caps cache miss for %s: %s:%s, %[2]s:%[4]s":                                  49,
	"error adding roster item %s: %v":                                             13,
	"error bootstraping history for %s: %v":                                       38,
	"error closing bookmarks stream: %v":                                          91,
	"error closing commands iter for %q: %v":                                      8,
	"error closing config file: %v":                                               65,
	"error copying early log data to output buffer: %q":                           70,
	"error creating keylog file: %q":                                              77,
	"error discovering bookmarks support: %v":                                     15,
	"error enabling carbons: %q":                                                  85,
	"error executing command %q on %q: %v":                                        5,
	"error fetching bookmarks: %q":                                                87,
	"error fetching commands for %q: %v":                                          7,
	"error fetching earliest message info for %v from database: %v":               29,
	"error fetching history after %s for %s: %v":                                  37,
	"error fetching info from cache: %v":                                          46,
	"error fetching roster: %q":                                                   86,
	"error fetching scrollback for %v: %v":                                        32,
	"error fetching version information: %v":                                      88,
	"error going offline: %v":                                                     12,
	"error inserting entity capbailities hash: %v":                                45,
	"error iterating over roster items: %v":                                       39,
	"error joining room %s: %v":                                                   25,
	"error loading chat: %v":                                                      26,
	"error logging to pane: %v":                                                   69,
	"error marking message %q as received: %v":                                    41,
	"error opening database: %v":                                                  68,
	"error parsing config file: %v":                                               64,
	"error parsing main account as XMPP address: %v":                              67,
	"error parsing timeout, defaulting to 30s: %q":                                76,
	"error parsing user address: %q":                                              75,
	"error publishing bookmark %s: %v":                                            17,
	"error publishing legacy bookmark %s: %v":                                     16,
	"error querying database for last seen messages: %v":                          36,
	"error querying history for %s: %v":                                           53,
	"error removing bookmark %s: %v":                                              19,
	"error removing legacy bookmark %s: %v":                                       18,
	"error removing roster item %s: %v":                                           14,
	"error retrieving roster version, falling back to full roster fetch: %v":      78,
	"error running password command, falling back to prompt: %v":                  72,
	"error saving entity caps to the database: %v":                                50,
	"error saving sent message to history: %v":                                    21,
	"error scrollback for %v: %v":                                                 33,
	"error sending message: %v":                                                   20,
	"error sending presence pre-approval to %s: %v":                               27,
	"error sending presence request to %s: %v":                                    28,
	"error setting away status: %v":                                               9,
	"error setting busy status: %v":                                               11,
	"error setting online status: %v":                                             10,
	"error showing next command for %q: %v":                                       6,
	"error updating roster version: %v":                                           40,
	"error updating to roster ver %q: %v":                                         35,
	"error writing history message to chat: %v":                                   43,
	"error writing history to database: %v":                                       44,
	"error writing history: %v":                                                   52,
	"error writing message to database: %v":                                       22,
	"error writing received message to chat: %v":                                  42,
	"executing command: %+v":                                                      4,
	"falling back to network query…":                                              47,
	"fetching scrollback before %v for %v…":                                       31,
	"got signal: %v":                                                              81,
	"initial login failed: %v":                                                    79,
	"invalid nick %s in config: %v":                                               23,
	"joining room %v…":                                                            24,
	"logged in as: %q":                                                            80,
	"no scrollback for %v":                                                        30,
	"no user address specified, edit %q and add:\n\n\tjid=\"me@example.com\"\n\n": 73,
	"override the account set in the config file":                                 59,
	"possibly spoofed history message from %s":                                    93,
	"print a default config file to stdout":                                       61,
	"print this help message":                                                     60,
	"running command: %q":                                                         71,
	"the config file to load":                                                     58,
	"unrecognized client event: %T(%[1]q)":                                        51,
	"unrecognized ui event: %T(%[1]q)":                                            34,
	"user address: %q":                                                            74,
}

var en_USIndex = []uint32{ // 117 elements
	// Entry 0 - 1F
	0x00000000, 0x00000005, 0x0000000a, 0x00000013,
	0x0000001a, 0x00000034, 0x00000062, 0x0000008e,
	0x000000b7, 0x000000e4, 0x00000105, 0x00000128,
	0x00000149, 0x00000164, 0x0000018a, 0x000001b2,
	0x000001dd, 0x0000020b, 0x00000232, 0x0000025e,
	0x00000283, 0x000002a0, 0x000002cc, 0x000002f5,
	0x00000319, 0x0000032f, 0x0000034f, 0x00000369,
	0x0000039d, 0x000003cc, 0x00000410, 0x00000428,
	// Entry 20 - 3F
	0x00000456, 0x00000481, 0x000004a3, 0x000004c7,
	0x000004f1, 0x00000527, 0x0000055b, 0x00000587,
	0x000005b0, 0x000005d5, 0x00000604, 0x00000632,
	0x0000065f, 0x00000688, 0x000006b8, 0x000006de,
	0x000006ff, 0x00000725, 0x00000759, 0x00000789,
	0x000007b1, 0x000007ce, 0x000007f6, 0x00000812,
	0x00000818, 0x0000081d, 0x00000822, 0x0000083a,
	0x00000866, 0x0000087e, 0x000008a4, 0x000008d1,
	// Entry 40 - 5F
	0x00000917, 0x00000938, 0x00000959, 0x00000980,
	0x000009b2, 0x000009d0, 0x000009ed, 0x00000a22,
	0x00000a39, 0x00000a77, 0x00000ac3, 0x00000ad7,
	0x00000af9, 0x00000b29, 0x00000b4b, 0x00000b95,
	0x00000bb1, 0x00000bc5, 0x00000bd7, 0x00000c00,
	0x00000c1b, 0x00000c3f, 0x00000c5d, 0x00000c7a,
	0x00000c9a, 0x00000cc4, 0x00000d10, 0x00000ddc,
	0x00000e02, 0x00000e25, 0x00000e51, 0x00000e5d,
	// Entry 60 - 7F
	0x00000e65, 0x00000e6a, 0x00000e73, 0x00000e80,
	0x00000e8e, 0x00000e96, 0x00000e9d, 0x00000ea2,
	0x00000ea7, 0x00000eac, 0x00000eb3, 0x00000ed9,
	0x00000eee, 0x00000f0d, 0x00000f12, 0x00000f17,
	0x00000f24, 0x00000f28, 0x00000f31, 0x00000f45,
	0x00000f4a,
} // Size: 492 bytes

const en_USData string = "" + // Size: 3914 bytes
	"\x02Prev\x02Next\x02Complete\x02Cancel\x02executing command: %+[1]v\x02e" +
	"rror executing command %[1]q on %[2]q: %[3]v\x02error showing next comma" +
	"nd for %[1]q: %[2]v\x02error fetching commands for %[1]q: %[2]v\x02error" +
	" closing commands iter for %[1]q: %[2]v\x02error setting away status: %[" +
	"1]v\x02error setting online status: %[1]v\x02error setting busy status: " +
	"%[1]v\x02error going offline: %[1]v\x02error adding roster item %[1]s: %" +
	"[2]v\x02error removing roster item %[1]s: %[2]v\x02error discovering boo" +
	"kmarks support: %[1]v\x02error publishing legacy bookmark %[1]s: %[2]v" +
	"\x02error publishing bookmark %[1]s: %[2]v\x02error removing legacy book" +
	"mark %[1]s: %[2]v\x02error removing bookmark %[1]s: %[2]v\x02error sendi" +
	"ng message: %[1]v\x02error saving sent message to history: %[1]v\x02erro" +
	"r writing message to database: %[1]v\x02invalid nick %[1]s in config: %[" +
	"2]v\x02joining room %[1]v…\x02error joining room %[1]s: %[2]v\x02error l" +
	"oading chat: %[1]v\x02error sending presence pre-approval to %[1]s: %[2]" +
	"v\x02error sending presence request to %[1]s: %[2]v\x02error fetching ea" +
	"rliest message info for %[1]v from database: %[2]v\x02no scrollback for " +
	"%[1]v\x02fetching scrollback before %[1]v for %[2]v…\x02error fetching s" +
	"crollback for %[1]v: %[2]v\x02error scrollback for %[1]v: %[2]v\x02unrec" +
	"ognized ui event: %[1]T(%[1]q)\x02error updating to roster ver %[1]q: %[" +
	"2]v\x02error querying database for last seen messages: %[1]v\x02error fe" +
	"tching history after %[1]s for %[2]s: %[3]v\x02error bootstraping histor" +
	"y for %[1]s: %[2]v\x02error iterating over roster items: %[1]v\x02error " +
	"updating roster version: %[1]v\x02error marking message %[1]q as receive" +
	"d: %[2]v\x02error writing received message to chat: %[1]v\x02error writi" +
	"ng history message to chat: %[1]v\x02error writing history to database: " +
	"%[1]v\x02error inserting entity capbailities hash: %[1]v\x02error fetchi" +
	"ng info from cache: %[1]v\x02falling back to network query…\x02caps cach" +
	"e hit for %[1]s: %[2]s:%[3]s\x02caps cache miss for %[1]s: %[2]s:%[3]s, " +
	"%[2]s:%[4]s\x02error saving entity caps to the database: %[1]v\x02unreco" +
	"gnized client event: %[1]T(%[1]q)\x02error writing history: %[1]v\x02err" +
	"or querying history for %[1]s: %[2]v\x04\x00\x02\x0a\x0a\x16\x02Usage of" +
	" communiqué:\x02DEBUG\x02RECV\x02SENT\x02the config file to load\x02over" +
	"ride the account set in the config file\x02print this help message\x02pr" +
	"int a default config file to stdout\x02Error encoding default config as " +
	"TOML: %[1]v\x02%[1]v\x0a\x0aTry running '%[2]s -config' to generate a de" +
	"fault config file.\x02error parsing config file: %[1]v\x02error closing " +
	"config file: %[1]v\x02account %[1]q not found in config file\x02error pa" +
	"rsing main account as XMPP address: %[1]v\x02error opening database: %[1" +
	"]v\x02error logging to pane: %[1]v\x02error copying early log data to ou" +
	"tput buffer: %[1]q\x02running command: %[1]q\x02error running password c" +
	"ommand, falling back to prompt: %[1]v\x04\x00\x02\x0a\x0aF\x02no user ad" +
	"dress specified, edit %[1]q and add:\x0a\x0a\x09jid=\x22me@example.com" +
	"\x22\x02user address: %[1]q\x02error parsing user address: %[1]q\x02erro" +
	"r parsing timeout, defaulting to 30s: %[1]q\x02error creating keylog fil" +
	"e: %[1]q\x02error retrieving roster version, falling back to full roster" +
	" fetch: %[1]v\x02initial login failed: %[1]v\x02logged in as: %[1]q\x02g" +
	"ot signal: %[1]v\x02Error while handling XMPP streams: %[1]q\x02Error go" +
	"ing offline: %[1]q\x02Error closing the connection: %[1]q\x02error enabl" +
	"ing carbons: %[1]q\x02error fetching roster: %[1]q\x02error fetching boo" +
	"kmarks: %[1]q\x02error fetching version information: %[1]v\x02To fix thi" +
	"s, contact your server administrator and ask them to enable %[1]q\x02You" +
	"r server does not support bookmark unification, an important feature tha" +
	"t stops newer clients from seeing a different list of chat rooms than ol" +
	"der clients that do not yet support the latest features.\x02error closin" +
	"g bookmarks stream: %[1]v\x02Error closing roster stream: %[1]q\x02possi" +
	"bly spoofed history message from %[1]s\x02Add Contact\x02Address\x02Name" +
	"\x02Channels\x02Conversation\x02Conversations\x02Offline\x02Online\x02Aw" +
	"ay\x02Busy\x02Logs\x02Remove\x02Remove this contact from your roster?" +
	"\x02Remove this channel?\x02Are you sure you want to quit?\x02Quit\x02Jo" +
	"in\x02Join Channel\x02Add\x02Commands\x02Loading commands…\x02Exec"

	// Total table size 4406 bytes (4KiB); checksum: 8197A6C6
