steps:
  info: &info
    image: golang:alpine
    environment:
      CGO_ENABLED: "0"
    commands:
      - go version
      - go env
  test:
    << : *info
    commands:
      - go test -v -cover ./...

when:
  - event: [tag, push, pull_request, release, manual]
    path:
      include: ['**/*.go', 'go.mod', 'go.sum']
depends_on:
  - dco
