pipeline:
  info: &info
    image: golang:${GO_VERSION}-alpine
    environment:
      CGO_ENABLED: "0"
    commands:
      - go version
      - go env
  test:
    << : *info
    commands:
      - go test -v -cover ./...

matrix:
  GO_VERSION:
    - 1.22
    - 1.23

depends_on:
  - dco
